### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by wassgha** [alexander-e-andrews/CSSeniorDisplayProject#10]
Continuous Integration would allow us to make sure new PRs don't break any exisiting functionality. A good Continuous Integration would compile the PR branch, run unit tests, run integration tests and run a linter to display code style mismatches.

### Tasks
- [x] Add TravisCI or CircleCI to the project
- [x] Create a minimal pipeline that simply compiles every PR and checks for fatal errors
- [x] Augment the pipeline with a linter
- [x] Augment the pipeline with test running once #19 is closed
