### ISSUE TITLE
[Master Issue] Slideshow Task Breakdown

### ISSUE THREAD

**Issue by wassgha** [alexander-e-andrews/CSSeniorDisplayProject#12]
By the end of the first sprint of this project, we would like to have a functioning slideshow and administrator interface that allows users to upload of photos and create an automatically looping slideshow.

This first iteration of the project **does not include** a login system (anyone having access to the admin url will be able to upload photos), slide ordering, multiple slideshows, multiple media types or widgets. These will come at later iterations of the project.

### Format for the slides
At the early stages of the sprint, the slideshow will take a static array of slides that will later be stored and edited in the database. Intitally, we can use this data template as an example of a slideshow:
```js
const slides = [
    {
      type: 'photo',
      data: 'https://compsci.lafayette.edu/wp-content/uploads/sites/66/2010/05/computerSci-homepage.jpg',
      title: 'Welcome to the Computer Science Department',
      desc: '',
      duration: 3, // In seconds
      order: 1
    },
    {
      type: 'photo',
      data: 'https://news.lafayette.edu/wp-content/blogs.dir/2/files/2018/12/STEM-professors-470x264.jpg',
      title: 'Hidden Figures Week',
      desc: 'Hidden Figures Week explored issues related to women in STEM through a roundtable faculty discussion.',
      duration: 10, // In seconds
      order: 3
    },
    {
      type: 'photo',
      data: 'https://news.lafayette.edu/wp-content/blogs.dir/2/files/2018/11/Chawne-Kimber-STEM-300x300.jpg',
      title: 'STEM Stars',
      desc: 'The future of STEM is here: Meet Lafayette’s innovators in science, technology, engineering, and mathematics.',
      duration: 3, // In seconds
      order: 2
    }    
  ]
```   
### Task Breakdown
- [x] #13 Slideshow component (given the static format above, shows the slides in order and transitions between them after the specified duration has elapsed)
- [x] #14 Simple administrative page (no log-in required for now)
- [x] #15 Drop-to-upload component (without backend)
- [x] #16 Set up an express API and a connection to a mongodb database hosted on mLab
- [x] #17 Set up mongodb schemas for the required collections and types
- [x] #18 Create an API endpoint for file uploading (ex. POST `/api/v1/slides`) which given a file, saves it on the server and creates a record on the database with default duration, title and description (editing the duration/title/description will come at a later stage)
- [x] Create an API endpoint for file listing (ex. GET `/api/v1/slides`)
- [x] #29 Create a user interface for listing slides (uploaded files)
- [x] Make the Slideshow component use the file listing API endpoint instead of a static list of slides
- [ ] Slide re-ordering
- [x] Stretch: Auto-refresh the display using socket.io on database update (see [here](https://stackoverflow.com/questions/35024814/nodejs-auto-refresh-view-after-database-updates) for an example)
- [x] Stretch: Create a user interface for re-ordering slides on the slideshow by drag n' drop
- [x] #26 Nit: Caching slides
- [x] #25 Nit: In-page navigation
