### ISSUE TITLE
[Master Issue] Widgets and Content Types

### ISSUE THREAD

**Issue by wassgha** [alexander-e-andrews/CSSeniorDisplayProject#31]
The more advanced phase of this project will expand the types of contents that slideshows can support from photos and videos to generic widget types (such as tweets, videos, websites, etc.). This functionality will also allow us to add the ability to simultaneously run a slideshow and standalone widgets side-to-side through a dynamic grid layout of the screen.

### Widgets Architecture

A widget can be either added to a Slideshow (with a duration) or be added directly to the screen (always visible).

The widget system architecture is composed of two major components: A "widget definition" and a "widget instance". 

**Widget Definitions**
The widget definition is hard coded into the codebase (not stored in the database): Each widget is a class that implements a `Widget` interface and contains a name and description of the widget, a method that renders the settings page of the widget, methods to serialize and deserialize information about the widget (to be stored in the database) and a method that renders the widget responsively, given the context. 

**Widget Instances**
Widget instances are the combination of a widget type and its particular configuration that is stored in the database (for example, for the weather widget this would be a widget of type "weather" and data "unit = Fahrenheit, location = Easton, PA"). Widget instances can be easily linked to a slideshow or a screen through a reference to their ID. The structure of the configuration data is variable from widget to widget and is defined by the serialization/deserialization methods of the **widget definition** . A widget instance will be treated the same way photos and videos are treated and can be referenced inside multiple slideshows at the same time.

### Ideas for widgets
The list is:
- Announcements widget (takes a background image, an icon and text, display the text on top of the image with the icon next to it)
- Google Calendar widget (displays daily events from a synced Google Calendar)
- Webpage widget (can be used to display webpage inside a tile, with the option for automatic scrolling with a configurable pace)
- List/Directory widget (lists the building's directory and rooms)
- Freeform editing widget (allows overlaying images, text and shapes with a WYSIWYG editor)
- Youtube widget (allows embedding Youtube videos)
- Calendar widget
- Countdown widget
- Twitter feed widget
- RSS feed widget
- Weather widget

### Task Breakdown
- [x] Create a structure (class interface) for defining widgets
- [x] Mongoose schemes for widget instances
- [x] Create initial sample widget types and their configuration forms
- [ ] Add a new content library page to the administrator panel that lists both uploaded files and "widget instances"
- [ ] Create a content library picker component that allows choosing widgets to add to a slideshow using a popunder/lightbox window
- [x] Integrate widgets within slides
- [x] Modify the Display component to support dynamic layouts
- [x] Create the Layout page with drag and drop widget adding (using the picker component)  and re-ordering
- [ ] Create more widget types
