### ISSUE TITLE
Widgets: Implement Widget-dependent Admin Panels

### ISSUE THREAD

**Issue by wassgha** [alexander-e-andrews/CSSeniorDisplayProject#58]
As a continuation of #55 , we need to implement a way for users to modify the individual configuration of each widget by clicking on the widget on the layout page. Once the user clicks on the widget, a dialog box will appear and render a form (provided by the developer of the widget) that allows the user to alter and save the widget instance's configuration.

### Task breakdown
- [x] Create a class that serves as an interface for defining and creating admin panels for widgets
- [x] Implement the user interface for the dialog box that appears when a user is modifying a widget
- [x] Implement configuration forms for the existing widgets
