### ISSUE TITLE
Google Calander Widget

### ISSUE THREAD

**Issue by alexander-e-andrews** [alexander-e-andrews/CSSeniorDisplayProject#69]
Widget that can read from Googles Calanders API:
https://developers.google.com/calendar/
Choose between today vs this week
### Task breakdown
- [ ] Create a google API endpoint
- [ ] Implement the widget to show data
- [ ] Implement the widget options panel to choose a calendar to link to
